// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[restaurant]/[menu]" | "/about" | "/admin" | "/admin/analytics" | "/admin/appearance" | "/admin/bookings" | "/admin/bookings/[id]" | "/admin/categories" | "/admin/checkout" | "/admin/login" | "/admin/menu" | "/admin/menu/category/[id]" | "/admin/onboarding" | "/admin/orders" | "/admin/orders/[id]" | "/admin/profile" | "/admin/qr" | "/admin/settings" | "/admin/signup" | "/admin/tables" | "/blog" | "/careers" | "/contact" | "/cookies" | "/forgot-password" | "/imprint" | "/login" | "/preview/[restaurant]/[menuId]" | "/privacy" | "/public-menu/[restaurant]" | "/public-menu/[restaurant]/[menuId]" | "/public-menu/[restaurant]/[menuId]/cart" | "/public-menu/[restaurant]/[menuId]/checkout" | "/public-menu/[restaurant]/[menuId]/checkout/order-summary" | "/r/[slug]" | "/r/[slug]/book-table" | "/r/[slug]/book-table/select-table" | "/reset-password" | "/signup" | "/terms"
type AppRouteHandlerRoutes = "/api/analytics" | "/api/appearance/save" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/register" | "/api/auth/reset-password" | "/api/bookings" | "/api/bookings/notify" | "/api/bookings/notify-status" | "/api/orders" | "/api/orders/notify" | "/api/restaurant/setup" | "/api/revalidate" | "/api/subscription/checkout" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[restaurant]/[menu]": { "restaurant": string; "menu": string; }
  "/about": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/appearance": {}
  "/admin/bookings": {}
  "/admin/bookings/[id]": { "id": string; }
  "/admin/categories": {}
  "/admin/checkout": {}
  "/admin/login": {}
  "/admin/menu": {}
  "/admin/menu/category/[id]": { "id": string; }
  "/admin/onboarding": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/profile": {}
  "/admin/qr": {}
  "/admin/settings": {}
  "/admin/signup": {}
  "/admin/tables": {}
  "/api/analytics": {}
  "/api/appearance/save": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/bookings": {}
  "/api/bookings/notify": {}
  "/api/bookings/notify-status": {}
  "/api/orders": {}
  "/api/orders/notify": {}
  "/api/restaurant/setup": {}
  "/api/revalidate": {}
  "/api/subscription/checkout": {}
  "/auth/callback": {}
  "/blog": {}
  "/careers": {}
  "/contact": {}
  "/cookies": {}
  "/forgot-password": {}
  "/imprint": {}
  "/login": {}
  "/preview/[restaurant]/[menuId]": { "restaurant": string; "menuId": string; }
  "/privacy": {}
  "/public-menu/[restaurant]": { "restaurant": string; }
  "/public-menu/[restaurant]/[menuId]": { "restaurant": string; "menuId": string; }
  "/public-menu/[restaurant]/[menuId]/cart": { "restaurant": string; "menuId": string; }
  "/public-menu/[restaurant]/[menuId]/checkout": { "restaurant": string; "menuId": string; }
  "/public-menu/[restaurant]/[menuId]/checkout/order-summary": { "restaurant": string; "menuId": string; }
  "/r/[slug]": { "slug": string; }
  "/r/[slug]/book-table": { "slug": string; }
  "/r/[slug]/book-table/select-table": { "slug": string; }
  "/reset-password": {}
  "/signup": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
