// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[restaurant]/[menu]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurant]/[menu]">> = Specific
  const handler = {} as typeof import("../../src/app/[restaurant]/[menu]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/appearance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/appearance">> = Specific
  const handler = {} as typeof import("../../src/app/admin/appearance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/admin/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/menu/category/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu/category/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/menu/category/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu">> = Specific
  const handler = {} as typeof import("../../src/app/admin/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/admin/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/qr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/qr">> = Specific
  const handler = {} as typeof import("../../src/app/admin/qr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/signup">> = Specific
  const handler = {} as typeof import("../../src/app/admin/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tables">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../src/app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/imprint/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/imprint">> = Specific
  const handler = {} as typeof import("../../src/app/imprint/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview/[restaurant]/[menuId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview/[restaurant]/[menuId]">> = Specific
  const handler = {} as typeof import("../../src/app/preview/[restaurant]/[menuId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/public-menu/[restaurant]/[menuId]/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public-menu/[restaurant]/[menuId]/cart">> = Specific
  const handler = {} as typeof import("../../src/app/public-menu/[restaurant]/[menuId]/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/public-menu/[restaurant]/[menuId]/checkout/order-summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public-menu/[restaurant]/[menuId]/checkout/order-summary">> = Specific
  const handler = {} as typeof import("../../src/app/public-menu/[restaurant]/[menuId]/checkout/order-summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/public-menu/[restaurant]/[menuId]/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public-menu/[restaurant]/[menuId]/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/public-menu/[restaurant]/[menuId]/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/public-menu/[restaurant]/[menuId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public-menu/[restaurant]/[menuId]">> = Specific
  const handler = {} as typeof import("../../src/app/public-menu/[restaurant]/[menuId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/public-menu/[restaurant]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public-menu/[restaurant]">> = Specific
  const handler = {} as typeof import("../../src/app/public-menu/[restaurant]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/r/[slug]/book-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/r/[slug]/book-table">> = Specific
  const handler = {} as typeof import("../../src/app/r/[slug]/book-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/r/[slug]/book-table/select-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/r/[slug]/book-table/select-table">> = Specific
  const handler = {} as typeof import("../../src/app/r/[slug]/book-table/select-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/r/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/r/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/r/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/appearance/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/appearance/save">> = Specific
  const handler = {} as typeof import("../../src/app/api/appearance/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/notify-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/notify-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/notify-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/restaurant/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/restaurant/setup">> = Specific
  const handler = {} as typeof import("../../src/app/api/restaurant/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../src/app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscription/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscription/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
