# ============================================
# DineEasy — Local Development Bootstrap (Windows)
# ============================================
# Usage: powershell -ExecutionPolicy Bypass -File scripts/setup.ps1

$ErrorActionPreference = "Stop"

function Write-Step($msg) {
    Write-Host "`n==> $msg" -ForegroundColor Cyan
}

function Test-Command($cmd) {
    return [bool](Get-Command $cmd -ErrorAction SilentlyContinue)
}

# ─── Preflight checks ───

Write-Step "Checking prerequisites..."

$missing = @()
if (-not (Test-Command "docker"))   { $missing += "Docker Desktop  -> https://docs.docker.com/desktop/install/windows-install/" }
if (-not (Test-Command "node"))     { $missing += "Node.js >=18    -> https://nodejs.org" }
if (-not (Test-Command "supabase")) { $missing += "Supabase CLI    -> npm install -g supabase" }

if ($missing.Count -gt 0) {
    Write-Host "`nMissing tools:" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
    Write-Host "`nInstall the above and re-run this script." -ForegroundColor Red
    exit 1
}

# Check Docker is running
$dockerInfo = docker info 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "Docker daemon is not running. Start Docker Desktop first." -ForegroundColor Red
    exit 1
}

Write-Host "All prerequisites met." -ForegroundColor Green

# ─── Install npm dependencies ───

Write-Step "Installing npm dependencies..."
npm install

# ─── Start Redis ───

Write-Step "Starting Redis via Docker Compose..."
docker compose up -d redis

# ─── Start Supabase ───

Write-Step "Starting local Supabase stack..."
supabase start

# ─── Extract keys from supabase status ───

Write-Step "Extracting Supabase credentials..."
$status = supabase status

$anon_key = ($status | Select-String "anon key:").ToString().Split("anon key:")[1].Trim()
$service_key = ($status | Select-String "service_role key:").ToString().Split("service_role key:")[1].Trim()
$api_url = ($status | Select-String "API URL:").ToString().Split("API URL:")[1].Trim()

# ─── Generate .env.local ───

Write-Step "Writing .env.local..."

$envContent = @"
# Auto-generated by scripts/setup.ps1 — $(Get-Date -Format "yyyy-MM-dd HH:mm")
NEXT_PUBLIC_SUPABASE_URL=$api_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon_key
SUPABASE_SERVICE_ROLE_KEY=$service_key
REDIS_URL=redis://127.0.0.1:6379
NEXT_PUBLIC_SITE_URL=http://localhost:3000
"@

Set-Content -Path ".env.local" -Value $envContent -Encoding UTF8

Write-Host ".env.local written successfully." -ForegroundColor Green

# ─── Summary ───

Write-Host "`n" -NoNewline
Write-Host "============================================" -ForegroundColor Green
Write-Host "  DineEasy local environment is ready!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Next.js      -> npm run dev         -> http://localhost:3000"
Write-Host "  Supabase API -> supabase status      -> $api_url"
Write-Host "  Studio       ->                      -> http://127.0.0.1:54323"
Write-Host "  Inbucket     -> (email testing)      -> http://127.0.0.1:54324"
Write-Host "  Redis        -> docker compose up -d -> redis://127.0.0.1:6379"
Write-Host ""
Write-Host "  Test login:  dev@dineeasy.local / password123"
Write-Host ""
