#!/usr/bin/env bash
# ============================================
# DineEasy — Local Development Bootstrap (macOS / Linux)
# ============================================
# Usage: chmod +x scripts/setup.sh && ./scripts/setup.sh

set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

step() { echo -e "\n${CYAN}==> $1${NC}"; }

# ─── Preflight checks ───

step "Checking prerequisites..."

missing=()
command -v docker    >/dev/null 2>&1 || missing+=("Docker      -> https://docs.docker.com/get-docker/")
command -v node      >/dev/null 2>&1 || missing+=("Node.js >=18 -> https://nodejs.org")
command -v supabase  >/dev/null 2>&1 || missing+=("Supabase CLI -> npm install -g supabase")

if [ ${#missing[@]} -gt 0 ]; then
    echo -e "${RED}Missing tools:${NC}"
    for m in "${missing[@]}"; do echo -e "  ${YELLOW}- $m${NC}"; done
    echo -e "${RED}Install the above and re-run this script.${NC}"
    exit 1
fi

docker info >/dev/null 2>&1 || { echo -e "${RED}Docker daemon is not running.${NC}"; exit 1; }

echo -e "${GREEN}All prerequisites met.${NC}"

# ─── Install npm dependencies ───

step "Installing npm dependencies..."
npm install

# ─── Start Supabase ───

step "Starting local Supabase stack..."
supabase start

# ─── Extract keys ───

step "Extracting Supabase credentials..."

api_url=$(supabase status | grep "API URL" | awk -F': ' '{print $2}' | xargs)
anon_key=$(supabase status | grep "anon key" | awk -F': ' '{print $2}' | xargs)
service_key=$(supabase status | grep "service_role key" | awk -F': ' '{print $2}' | xargs)

# ─── Generate .env.local ───

step "Writing .env.local..."

cat > .env.local <<EOF
# Auto-generated by scripts/setup.sh — $(date '+%Y-%m-%d %H:%M')
NEXT_PUBLIC_SUPABASE_URL=${api_url}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon_key}
SUPABASE_SERVICE_ROLE_KEY=${service_key}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
EOF

echo -e "${GREEN}.env.local written successfully.${NC}"

# ─── Summary ───

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  DineEasy local environment is ready!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "  Next.js      -> npm run dev         -> http://localhost:3000"
echo "  Supabase API -> supabase status      -> ${api_url}"
echo "  Studio       ->                      -> http://127.0.0.1:54323"
echo "  Inbucket     -> (email testing)      -> http://127.0.0.1:54324"
echo ""
echo "  Test login:  dev@dineeasy.local / password123"
echo ""
